version: '3.3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    container_name: mariadb
    hostname: mariadb
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3'
    restart: always
    container_name: moodle
    hostname: moodle
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME= admin
      - MOODLE_PASSWORD= ausias38
    volumes:
      - 'moodle_data:/bitnami'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
