version: '3.5'
services:
   wiki:
    container_name: dokuwiki
    image: nanih98/dokuwiki
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/dokuwiki:/bitnami
    environment:
      - DOKUWIKI_USERNAME=username
      - DOKUWIKI_FULL_NAME=Devopstech Docs    
      - DOKUWIKI_PASSWORD=pass
      - DOKUWIKI_EMAIL=info@devopstech.org
      - DOKUWIKI_WIKI_NAME=Devopstech
