FROM alpine:3.8

MAINTAINER Daniel Cascales Romero <devopstech253@gmail.com>
LABEL name="nanih98/alpine:3.8"
LABEL description=""

RUN apk add --update \
  bash \
  su-exec \
  wget curl \
  vim joe \
  && rm -rf /var/cache/apk/*

# Default entrypoint
ADD files/entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh
ENTRYPOINT ["/root/entrypoint.sh"]
