version: '3.6'
services:
  jenkins:
    container_name: jenkins
    hostname: jenkins-master
    restart: always
    ports:
      - "80:8080"
    image: jenkins/jenkins:alpine
    volumes:
      - /srv/jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m"
