version: '3.5'
services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    ports:
      - "80:8080"
    image: jenkins/jenkins:lts
    volumes:
      - /srv/jenkins_home:/var/jenkins_home # watch out! Possibly there will be problems with the jenkins mapped volumes, execute the commands that I specify in the post.
